-- ========================================
-- CORRECT DIAGNOSTIC SCRIPT FOR tee@gmail.com
-- ========================================
-- Based on ACTUAL database structure from your export
-- This queries the tables that ACTUALLY EXIST

-- ============================================
-- STEP 1: Check if public.users table exists
-- ============================================
SELECT EXISTS (
  SELECT FROM information_schema.tables 
  WHERE table_schema = 'public' 
  AND table_name = 'users'
) as users_table_exists;

-- ============================================
-- STEP 2: Check contractor record (THIS IS WHERE SUBSCRIPTION DATA IS!)
-- ============================================
SELECT 
  'CONTRACTOR DATA' as section,
  id,
  email,
  company_name,
  cidb_grade,
  subscription_tier,
  subscription_status,
  billing_cycle,
  subscription_start_date,
  next_billing_date,
  status as approval_status,
  is_active,
  created_at
FROM public.contractors
WHERE LOWER(email) = LOWER('tee@gmail.com');

-- ============================================
-- STEP 3: Check auth.users record
-- ============================================
SELECT 
  'AUTH USER DATA' as section,
  id,
  email,
  email_confirmed_at,
  created_at,
  raw_user_meta_data->>'user_type' as user_type,
  raw_user_meta_data->>'company_name' as company_name
FROM auth.users
WHERE LOWER(email) = LOWER('tee@gmail.com');

-- ============================================
-- STEP 4: Count BOQs generated by tee@gmail.com
-- ============================================
SELECT 
  'BOQ COUNT' as section,
  COUNT(*) as total_boqs_generated,
  MIN(created_at) as first_boq_date,
  MAX(created_at) as most_recent_boq_date,
  SUM(total_cost::numeric) as total_value_generated
FROM public.bills b
JOIN auth.users u ON b.user_id = u.id
WHERE LOWER(u.email) = LOWER('tee@gmail.com');

-- ============================================
-- STEP 5: List all BOQs by tee@gmail.com
-- ============================================
SELECT 
  'BOQ DETAILS' as section,
  b.id,
  b.project_name,
  b.bill_number,
  b.total_cost,
  b.status,
  b.created_at,
  b.uploaded_via
FROM public.bills b
JOIN auth.users u ON b.user_id = u.id
WHERE LOWER(u.email) = LOWER('tee@gmail.com')
ORDER BY b.created_at DESC;

-- ============================================
-- STEP 6: Check if public.users has data (if table exists)
-- ============================================
-- This will error if public.users doesn't exist - that's OK!
-- It tells us the table doesn't exist.
SELECT 
  'PUBLIC USERS DATA (IF EXISTS)' as section,
  *
FROM public.users
WHERE LOWER(email) = LOWER('tee@gmail.com');

-- ============================================
-- EXPECTED RESULTS
-- ============================================
-- 
-- If tee@gmail.com is a contractor with FREE tier:
-- - contractors.subscription_tier = 'FREE'
-- - contractors.subscription_status = 'trial'
-- - Trial limit should be 3 BOQs
-- 
-- If they generated BOQs, count should show how many
-- If count >= 3, they should see upgrade prompt
-- 
-- If STEP 6 errors with "relation does not exist",
-- it means public.users table doesn't exist and you should
-- use contractors table for subscription data
