-- ========================================
-- DIAGNOSTIC SCRIPT FOR tee@gmail.com
-- ========================================
-- Run this in Supabase SQL Editor to see why trial counter isn't working

-- 1. Check contractors table for tee@gmail.com (THIS HAS SUBSCRIPTION DATA!)
SELECT 
  'CONTRACTOR DATA' as section,
  id,
  email,
  company_name,
  subscription_tier,
  subscription_status,
  billing_cycle,
  is_active,
  created_at
FROM public.contractors
WHERE LOWER(email) = LOWER('tee@gmail.com');

-- 2. Check auth.users table for tee@gmail.com
SELECT 
  'AUTH USER DATA' as section,
  id,
  email,
  created_at,
  raw_user_meta_data->>'user_type' as user_type,
  raw_user_meta_data->>'company_name' as company_name
FROM auth.users
WHERE LOWER(email) = LOWER('tee@gmail.com');

-- 3. Check all BOQs generated by tee@gmail.com
-- NOTE: bills table has user_id (UUID), NOT user_email, so we need to JOIN
SELECT 
  'BOQ DETAILS' as section,
  b.id,
  b.project_name,
  b.bill_number,
  b.total_cost,
  b.status,
  b.created_at
FROM public.bills b
JOIN auth.users u ON b.user_id = u.id
WHERE LOWER(u.email) = LOWER('tee@gmail.com')
ORDER BY b.created_at DESC;

-- 4. Count BOQs generated
SELECT 
  'BOQ COUNT' as section,
  COUNT(*) as total_boqs_generated,
  MIN(b.created_at) as first_boq,
  MAX(b.created_at) as last_boq
FROM public.bills b
JOIN auth.users u ON b.user_id = u.id
WHERE LOWER(u.email) = LOWER('tee@gmail.com');