-- ========================================
-- FIX ALL TRIAL COUNTERS - COMPREHENSIVE FIX
-- ========================================
-- This script ensures ALL contractors have proper trial billing setup
-- Run this in Supabase SQL Editor

-- Step 1: Show current state of ALL contractors
SELECT 
  '=== BEFORE FIX ===' as status,
  c.email,
  c.subscription_tier,
  c.subscription_status,
  c.billing_cycle,
  (SELECT COUNT(*) FROM public.bills b 
   JOIN auth.users u ON b.user_id = u.id 
   WHERE u.email = c.email) as boqs_generated
FROM public.contractors c
ORDER BY c.email;

-- Step 2: Fix contractors with missing trial_bills_remaining
UPDATE public.contractors
SET trial_bills_remaining = 3
WHERE trial_bills_remaining IS NULL
  AND subscription_tier IN ('FREE', 'free_trial')
  AND (is_premium IS NULL OR is_premium = false);

-- Step 3: Ensure FREE tier contractors have proper subscription_tier set
UPDATE public.contractors
SET subscription_tier = 'FREE'
WHERE subscription_tier IS NULL
  AND (is_premium IS NULL OR is_premium = false);

-- Step 4: Fix specific contractors who generated BOQs but counter didn't decrease
-- These contractors should have their counter set based on how many BOQs they generated
DO $$
DECLARE
  contractor_record RECORD;
  boq_count INTEGER;
BEGIN
  FOR contractor_record IN 
    SELECT id, email, subscription_tier, trial_bills_remaining
    FROM public.contractors
    WHERE subscription_tier IN ('FREE', 'free_trial')
      AND (is_premium IS NULL OR is_premium = false)
  LOOP
    -- Count BOQs generated by this contractor
    SELECT COUNT(*) INTO boq_count
    FROM public.bills b
    JOIN auth.users u ON b.user_id = u.id
    WHERE u.email = contractor_record.email;
    
    -- Calculate remaining trials (3 - generated, but not less than 0)
    DECLARE
      calculated_remaining INTEGER;
    BEGIN
      calculated_remaining := GREATEST(0, 3 - boq_count);
      
      -- Only update if different from current value
      IF contractor_record.trial_bills_remaining IS NULL OR 
         contractor_record.trial_bills_remaining != calculated_remaining THEN
        
        UPDATE public.contractors
        SET trial_bills_remaining = calculated_remaining
        WHERE id = contractor_record.id;
        
        RAISE NOTICE '✅ Fixed % - Generated % BOQs, set counter to %', 
          contractor_record.email, boq_count, calculated_remaining;
      END IF;
    END;
  END LOOP;
END $$;

-- Step 5: Show AFTER fix state
SELECT 
  '=== AFTER FIX ===' as status,
  email,
  subscription_tier,
  trial_bills_remaining,
  is_premium,
  (SELECT COUNT(*) FROM public.bills WHERE user_email = users.email) as boqs_generated,
  CASE 
    WHEN trial_bills_remaining = 0 THEN '⚠️ Trial exhausted - should see upgrade prompt'
    WHEN trial_bills_remaining = 3 THEN '✅ Full trial available'
    WHEN trial_bills_remaining BETWEEN 1 AND 2 THEN '⚡ Trial in progress'
    ELSE '❌ ISSUE: Invalid trial count'
  END as status_check
FROM public.users
ORDER BY email;

-- Step 6: Verify contractors with free_trial tier
SELECT 
  '=== CONTRACTORS ===' as status,
  c.email,
  c.company_name,
  c.subscription_tier as contractor_tier,
  c.status as contractor_status,
  u.subscription_tier as user_tier,
  u.trial_bills_remaining,
  u.is_premium,
  (SELECT COUNT(*) FROM public.bills WHERE user_email = c.email) as boqs_generated
FROM public.contractors c
LEFT JOIN public.users u ON c.email = u.email
WHERE c.subscription_tier = 'free_trial'
ORDER BY c.email;

-- ========================================
-- EXPECTED RESULTS
-- ========================================
-- After running this script:
-- 1. All FREE/free_trial contractors have trial_bills_remaining set correctly
-- 2. tee@gmail.com should have: 3 - (number of BOQs generated)
-- 3. bone@gmail.com should have: 3 - (number of BOQs generated)
-- 4. All contractors with free_trial tier should have proper counters
-- 
-- If a contractor generated 5 BOQs but counter was stuck at 3:
-- - Counter will now be 0 (3 - 5 = -2, but GREATEST(0, -2) = 0)
-- - Contractor will see upgrade prompt on next login