-- =====================================================
-- FIX TRIAL BILLING COUNTER ISSUE
-- =====================================================
-- This script diagnoses and fixes the trial billing counter
-- for contractors who are stuck at 3 trial bills remaining
-- even after generating multiple BOQs.
-- =====================================================

-- STEP 1: Diagnose the issue
-- =====================================================

-- Check current state of bone@gmail.com contractor
SELECT 
  'bone@gmail.com current state' AS check_type,
  u.id,
  u.email,
  u.subscription_tier,
  u.trial_bills_remaining,
  u.is_premium,
  COUNT(b.id) AS total_bills_generated
FROM users u
LEFT JOIN bills b ON b.user_id = u.id
WHERE u.email = 'bone@gmail.com'
GROUP BY u.id, u.email, u.subscription_tier, u.trial_bills_remaining, u.is_premium;

-- Check all bills generated by bone@gmail.com
SELECT 
  'Bills generated by bone@gmail.com' AS check_type,
  id,
  bill_number,
  project_name,
  total_cost,
  created_at,
  uploaded_via
FROM bills
WHERE user_id = (SELECT id FROM users WHERE email = 'bone@gmail.com')
ORDER BY created_at DESC;

-- Check if there are any users with stuck trial counters (generated bills but counter still at 3)
SELECT 
  'Users with stuck trial counters' AS check_type,
  u.email,
  u.subscription_tier,
  u.trial_bills_remaining,
  COUNT(b.id) AS bills_generated,
  CASE 
    WHEN COUNT(b.id) > 0 AND u.trial_bills_remaining = 3 THEN '⚠️ STUCK AT 3'
    WHEN COUNT(b.id) >= u.trial_bills_remaining THEN '✅ SHOULD BE 0'
    ELSE '✅ OK'
  END AS status
FROM users u
LEFT JOIN bills b ON b.user_id = u.id
WHERE u.subscription_tier = 'FREE'
GROUP BY u.id, u.email, u.subscription_tier, u.trial_bills_remaining
HAVING COUNT(b.id) > 0;

-- STEP 2: Fix bone@gmail.com specifically
-- =====================================================

-- Calculate the correct trial_bills_remaining for bone@gmail.com
-- based on bills already generated
UPDATE users
SET trial_bills_remaining = GREATEST(0, 3 - (
  SELECT COUNT(*) FROM bills WHERE bills.user_id = users.id
))
WHERE email = 'bone@gmail.com'
  AND subscription_tier = 'FREE';

-- STEP 3: Fix ALL users with stuck trial counters
-- =====================================================

-- Recalculate trial_bills_remaining for ALL FREE tier users
-- based on actual bills generated
UPDATE users
SET trial_bills_remaining = GREATEST(0, 3 - (
  SELECT COUNT(*) FROM bills WHERE bills.user_id = users.id
))
WHERE subscription_tier = 'FREE'
  AND trial_bills_remaining > 0;

-- STEP 4: Verify the fix
-- =====================================================

-- Check bone@gmail.com after fix
SELECT 
  '✅ bone@gmail.com AFTER FIX' AS check_type,
  u.id,
  u.email,
  u.subscription_tier,
  u.trial_bills_remaining AS remaining,
  COUNT(b.id) AS bills_generated,
  CASE 
    WHEN u.trial_bills_remaining = GREATEST(0, 3 - COUNT(b.id)) 
    THEN '✅ CORRECT' 
    ELSE '❌ STILL WRONG' 
  END AS status
FROM users u
LEFT JOIN bills b ON b.user_id = u.id
WHERE u.email = 'bone@gmail.com'
GROUP BY u.id, u.email, u.subscription_tier, u.trial_bills_remaining;

-- Check all FREE tier users after fix
SELECT 
  '✅ ALL FREE TIER USERS AFTER FIX' AS check_type,
  u.email,
  u.trial_bills_remaining AS remaining,
  COUNT(b.id) AS bills_generated,
  GREATEST(0, 3 - COUNT(b.id)) AS should_be,
  CASE 
    WHEN u.trial_bills_remaining = GREATEST(0, 3 - COUNT(b.id)) 
    THEN '✅ CORRECT' 
    ELSE '❌ MISMATCH' 
  END AS status
FROM users u
LEFT JOIN bills b ON b.user_id = u.id
WHERE u.subscription_tier = 'FREE'
GROUP BY u.id, u.email, u.trial_bills_remaining
ORDER BY status DESC, u.email;

-- STEP 5: Optional - Show summary statistics
-- =====================================================

SELECT 
  'TRIAL BILLING SUMMARY' AS report_type,
  COUNT(DISTINCT u.id) AS total_free_users,
  COUNT(DISTINCT CASE WHEN b.id IS NOT NULL THEN u.id END) AS users_with_bills,
  SUM(CASE WHEN u.trial_bills_remaining = 0 THEN 1 ELSE 0 END) AS users_exhausted_trial,
  SUM(CASE WHEN u.trial_bills_remaining > 0 THEN 1 ELSE 0 END) AS users_with_trial_remaining
FROM users u
LEFT JOIN bills b ON b.user_id = u.id
WHERE u.subscription_tier = 'FREE';

-- =====================================================
-- INSTRUCTIONS FOR USE:
-- =====================================================
-- 1. Copy this entire script
-- 2. Go to your Supabase Dashboard → SQL Editor
-- 3. Paste the script
-- 4. Click "Run" to execute
-- 5. Review the diagnostic output to confirm the fix worked
-- 6. The code changes in MainDashboard.tsx will now work correctly
-- =====================================================

-- =====================================================
-- WHAT THIS FIXES:
-- =====================================================
-- ✅ Corrects trial_bills_remaining for bone@gmail.com
-- ✅ Fixes ALL users with stuck trial counters
-- ✅ Ensures counter matches actual bills generated
-- ✅ Code in MainDashboard.tsx will now decrement correctly
-- =====================================================
