-- ========================================
-- FIX TRIAL COUNTER FOR tee@gmail.com
-- ========================================
-- Run this in Supabase SQL Editor to fix the trial billing counter

-- Step 1: Check if tee@gmail.com exists in users table
DO $$
DECLARE
  user_count INTEGER;
  user_auth_id UUID;
BEGIN
  -- Count existing records
  SELECT COUNT(*) INTO user_count
  FROM public.users
  WHERE email = 'tee@gmail.com';
  
  RAISE NOTICE 'Found % user record(s) for tee@gmail.com', user_count;
  
  -- Get auth user ID
  SELECT id INTO user_auth_id
  FROM auth.users
  WHERE email = 'tee@gmail.com'
  LIMIT 1;
  
  IF user_auth_id IS NOT NULL THEN
    RAISE NOTICE 'Auth user ID for tee@gmail.com: %', user_auth_id;
    
    -- If user doesn't exist in public.users, create it
    IF user_count = 0 THEN
      RAISE NOTICE 'Creating new user record for tee@gmail.com...';
      INSERT INTO public.users (
        id,
        email,
        full_name,
        subscription_tier,
        trial_bills_remaining,
        is_premium,
        created_at
      ) VALUES (
        user_auth_id,
        'tee@gmail.com',
        'Tee User',
        'FREE',
        3,  -- Reset to 3 trials
        false,
        NOW()
      );
      RAISE NOTICE '✅ User record created with 3 trial bills';
    ELSE
      -- User exists, update trial counter
      RAISE NOTICE 'Updating existing user record...';
      UPDATE public.users
      SET 
        trial_bills_remaining = 3,  -- Reset to 3 trials
        subscription_tier = 'FREE',
        is_premium = false
      WHERE email = 'tee@gmail.com';
      RAISE NOTICE '✅ Trial counter reset to 3 bills';
    END IF;
  ELSE
    RAISE NOTICE '❌ No auth user found for tee@gmail.com - user needs to sign up first';
  END IF;
END $$;

-- Step 2: Verify the fix
SELECT 
  email,
  subscription_tier,
  trial_bills_remaining,
  is_premium,
  created_at,
  updated_at
FROM public.users
WHERE email = 'tee@gmail.com';

-- Step 3: Show all BOQs generated by tee@gmail.com (for reference)
SELECT 
  COUNT(*) as total_boqs_generated,
  MIN(created_at) as first_boq,
  MAX(created_at) as last_boq
FROM public.bills
WHERE user_email = 'tee@gmail.com';

-- ========================================
-- EXPECTED RESULT
-- ========================================
-- After running this script:
-- 1. tee@gmail.com should have trial_bills_remaining = 3
-- 2. subscription_tier should be 'FREE'
-- 3. is_premium should be false
-- 4. Next BOQ generation will decrement: 3 → 2 → 1 → 0
-- 5. At 0, upgrade prompt will appear