/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zzdzrlglivtpawtitvgu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6ZHpybGdsaXZ0cGF3dGl0dmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MTQwMjcsImV4cCI6MjA4NjQ5MDAyN30.UL45C5S7SDnjk--WxGrERukNEldPkAxQKavGRkI65yc"