/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tjajhzepupsmunewfvag"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqYWpoemVwdXBzbXVuZXdmdmFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxMDAyODQsImV4cCI6MjA4NDY3NjI4NH0.pv5EOy4gGiQUEKt6tA_BCBC_1kO22cDYF5aCTs0LH9k"

// Helper function to get Supabase config for any environment
export function getSupabaseConfig(environment: string) {
  return {
    projectId: projectId,
    projectUrl: `https://${projectId}.supabase.co`,
    publicAnonKey: publicAnonKey,
  };
}