create table if not exists public.historical_boq_rates (
  id bigint generated by default as identity primary key,
  description text not null,
  unit text not null,
  rate numeric(14,2) not null check (rate > 0),
  category text not null,
  province_code text not null,
  supplier text not null,
  quote_date date not null,
  source_reference text not null,
  page_reference text not null,
  price_basis text not null,
  status text not null default 'pending' check (status in ('reviewed','pending','rejected')),
  created_at timestamptz not null default now(),
  unique (description, unit, rate, source_reference, page_reference)
);

alter table public.historical_boq_rates enable row level security;
revoke all on public.historical_boq_rates from anon;
grant select on public.historical_boq_rates to authenticated;

drop policy if exists "Authenticated users can read reviewed historical rates" on public.historical_boq_rates;
create policy "Authenticated users can read reviewed historical rates"
  on public.historical_boq_rates for select to authenticated
  using (status = 'reviewed');

create index if not exists historical_boq_rates_lookup_idx
  on public.historical_boq_rates (status, province_code, unit);

insert into public.historical_boq_rates
  (description, unit, rate, category, province_code, supplier, quote_date, source_reference, page_reference, price_basis, status)
values
  ('uPVC pipe 200mm Class 12', 'm', 258.10, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC pipe 160mm Class 12', 'm', 165.50, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC pipe 110mm Class 12', 'm', 78.35, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC pipe 90mm Class 12', 'm', 63.20, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC pipe 75mm Class 12', 'm', 44.35, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC pipe 63mm Class 12', 'm', 31.15, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC pipe 200mm Class 9', 'm', 198.40, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC pipe 160mm Class 9', 'm', 126.60, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC pipe 110mm Class 9', 'm', 60.55, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC pipe 75mm Class 9', 'm', 33.85, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC pipe 160mm Class 6', 'm', 86.80, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC pipe 110mm Class 6', 'm', 40.70, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC pipe 90mm Class 6', 'm', 33.65, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC pipe 75mm Class 6', 'm', 22.85, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC pipe 63mm Class 6', 'm', 16.55, 'pipe', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('cast iron end cap 200mm', 'No.', 894.67, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('cast iron end cap 160mm', 'No.', 528.00, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('cast iron end cap 110mm', 'No.', 318.67, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('cast iron end cap 90mm', 'No.', 258.67, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('cast iron end cap 75mm', 'No.', 180.00, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('cast iron end cap 63mm', 'No.', 138.67, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 4', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('cast iron equal tee 200mm', 'No.', 2316.00, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 5', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('cast iron equal tee 160mm', 'No.', 1405.33, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 5', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('cast iron equal tee 110mm', 'No.', 689.33, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 5', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('cast iron equal tee 90mm', 'No.', 545.33, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 5', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('cast iron equal tee 75mm', 'No.', 460.00, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 5', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('cast iron equal tee 63mm', 'No.', 328.00, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 5', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC Class 16 bend 110mm 90 degree', 'No.', 310.50, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 5', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC Class 16 bend 160mm 90 degree', 'No.', 691.53, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 5', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('uPVC Class 16 bend 200mm 90 degree', 'No.', 1245.07, 'fitting', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 5', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('gate valve 200mm', 'No.', 9093.33, 'valve', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 6', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('gate valve 160mm', 'No.', 5368.00, 'valve', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 6', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('gate valve 110mm', 'No.', 3086.67, 'valve', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 6', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('gate valve 75mm', 'No.', 2482.67, 'valve', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 6', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('gate valve 63mm', 'No.', 1760.00, 'valve', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 6', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed'),
  ('pipeline marker', 'No.', 500.00, 'marker', 'LP', 'Sekunjalo Piping Projects (Pty) Ltd', '2026-02-26', 'Ngovhela Phase 2A supplier quotation', 'page 6', 'Delivered to site, not offloaded; VAT excluded; historical quotation', 'reviewed')
on conflict do nothing;

comment on table public.historical_boq_rates is
  'Private reviewed historical quotations used as priority-1 BOQ matching evidence; source documents are not stored or redistributed.';
